# 服务配置
server:
  port: 8888
# spring配置
spring:
  # 1.应用配置
  application:
    name: jkshop #指定服务名
    # 2.数据库连接池
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jkshop?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:      maximum-pool-size: 30
      minimum-idle: 10
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.jkshop.mysqldemo.dao